services:
  - type: web
    name: rakshak
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_USER
        value: 2BZF1MGHQnAAGmx.root
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: test
      - key: DB_SSL
        value: "true"
      - key: KEEP_ALIVE_URL
        value: https://rakshak-u4ev.onrender.com/health
